spring:
  application:
    name: nucleo-service
  datasource:
    url: jdbc:postgresql://localhost:5440/ultimamilla_nucleo
    username: ultimamilla
    password: ultimamilla
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8090